//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Company
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Construction_CompanyEntities : DbContext
    {
        public Construction_CompanyEntities()
            : base("name=Construction_CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Бригадиры> Бригадиры { get; set; }
        public virtual DbSet<Бригады> Бригады { get; set; }
        public virtual DbSet<График_работ> График_работ { get; set; }
        public virtual DbSet<Здания> Здания { get; set; }
        public virtual DbSet<Использование_материалов> Использование_материалов { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Рабочие> Рабочие { get; set; }
        public virtual DbSet<Типы_зданий> Типы_зданий { get; set; }
    }
}
