//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бригадиры
    {
        public int ID_Бригадира { get; set; }
        public string Имя_бригадира { get; set; }
        public Nullable<int> ID_Бригады { get; set; }
    
        public virtual Бригады Бригады { get; set; }
    }
}
