//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class График_работ
    {
        public int ID_Графика { get; set; }
        public Nullable<int> ID_Здания { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
    
        public virtual Здания Здания { get; set; }
    }
}
