//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материалы()
        {
            this.Использование_материалов = new HashSet<Использование_материалов>();
        }
    
        public int ID_Материала { get; set; }
        public string Название_материала { get; set; }
        public Nullable<int> Количество_на_складе { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Использование_материалов> Использование_материалов { get; set; }
    }
}
